#spring:
#  datasource:
#    dynamic:
#      primary: db1 #设置默认数据源
#      strict: false #未匹配到数据源时使用默认数据源
#      datasource:
#        db1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://localhost:3306/mes?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#          username: root
#          password: root123456
##        db2:
##          driver-class-name: com.mysql.cj.jdbc.Driver
##          url: jdbc:mysql://192.168.0.106:3306/ego?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
##          username: mes
##          password: zy@123
##        db3:
##          driver-class-name: oracle.jdbc.driver.OracleDriver
##          url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
##          username: system
##          password: manager1
#enable:
#  scheduling: true
#logging:
#  config: classpath:log4j2-dev.yml
#  level:
#    root: INFO
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
