#spring:
#  datasource:
#    dynamic:
#      primary: db1 #设置默认数据源
#      strict: false #未匹配到数据源时使用默认数据源
#      datasource:
#        db1:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://127.0.0.1:3306/mes?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#          username: root
#          password: root@zhongyu
#        db2:
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://182.192.0.9:3306/ego?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#          username: ego
#          password: egorobotics
##        db3:
##          driver-class-name: oracle.jdbc.driver.OracleDriver
##          url: jdbc:oracle:thin:@127.0.0.1:1521:orcl
##          username: system
##          password: sys
#server:
#  port: 6000
#jbtcl:
#  local:
#    ding-talk:
#      app-key: dingglpralajg1sgfxnd
#      app-secret: aXrBuir70ckHF0dWxnxuRcG3TUO4LTku5DSNZXgbslZzubNcOSlWHrlQy1EfSXQ6
#      agent-id: 2367916722
